# Generated by Django 3.2.6 on 2021-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default='', max_length=200)),
                ('sex', models.CharField(default='', max_length=200)),
                ('bloodg', models.CharField(default='', max_length=200)),
                ('disease', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
