# Generated by Django 3.2.6 on 2021-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=''),
        ),
    ]
